apiVersion: apps/v1
kind: Deployment
metadata:
  name: spot-app
  namespace: workshop
  labels:
    app: spot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spot
  template:
    metadata:
      labels:
        app: spot
    spec:
      containers:
      - name: spot-service
        image: lobostome/spot:v1
        ports:
        - containerPort: 8080
